baseURL = 'https://michelleespranita.github.io/'
languageCode = 'en-us'
title = "Michelle Espranita Liman"
theme = "paper"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'michelleespranita'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'michelleespra'             # linkedin.com/in/YOUR_LINKEDIN_ID


